version: '3.7'
services:
  dev:
    build:
      context: .
      target: gatsby
    ports:
      - "9929:9929"
      - "9230:9230"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command:  ["gatsby", "develop", "-H", "0.0.0.0"]
  # Had to add a proxy as gatsby seems to refuse connections if they're to a different IP than it's listening on
  # Proxies both http and websockets
  proxy:
    image: nginx:1.17.5-alpine
    ports:
      - "8000:8000"
    command: >
      sh -c 'echo "server { \
        listen       8000;\
        server_name  dev;\
        location / {\
          proxy_pass      http://dev:8000;\
          proxy_http_version 1.1; \
          proxy_set_header Upgrade \$$http_upgrade; \
          proxy_set_header Connection "Upgrade"; \
        } \
      }" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
volumes:
  node_modules: